<node id="c0"
      text="c0" />

<node id="c1"
      text="c1" />

<node id="c2"
      text="c2" />

<node id="c3"
      text="c3" />

<node id="c4"
      text="c4" />

<node id="c5"
      text="c5" />

<node id="c6"
      text="c6" />

<node id="c7"
      text="c7" />

<edge id="c0-c2"
      src_port="c0"
      dest_port="c2" />

<edge id="c1-c2"
      src_port="c1"
      dest_port="c2" />

<edge id="c2-c3"
      src_port="c2"
      dest_port="c3" />

<edge id="c4-c1"
      src_port="c4"
      dest_port="c1" />

<edge id="c3-c4"
      src_port="c3"
      dest_port="c4" />

<edge id="c7-c4"
      src_port="c7"
      dest_port="c4" />

<edge id="c6-c7"
      src_port="c6"
      dest_port="c7" />

<edge id="c7-c6"
      src_port="c7"
      dest_port="c6" />

<edge id="c5-c6"
      src_port="c5"
      dest_port="c6" />
