<node id="0"
      text="0" />

<node id="1"
      text="1" />

<node id="2"
      text="2" />

<node id="3"
      text="3" />

<edge id="c0-c2"
      src_port="c0"
      dest_port="c2" />

<edge id="c1-c2"
      src_port="c1"
      dest_port="c2" />

<edge id="c2-c3"
      src_port="c2"
      dest_port="c3" />

<edge id="c4-c1"
      src_port="c4"
      dest_port="c1" />

<edge id="c3-c4"
      src_port="c3"
      dest_port="c4" />

<edge id="c7-c4"
      src_port="c7"
      dest_port="c4" />

<edge id="c6-c7"
      src_port="c6"
      dest_port="c7" />

<edge id="c7-c6"
      src_port="c7"
      dest_port="c6" />

<edge id="c5-c6"
      src_port="c5"
      dest_port="c6" />
