<info	title="Example"
		date="25/06/2007" />

<node	id="c0"
		text="c0" />

<node	id="c1"
		text="c1" />

<node	id="c2"
		text="c2" />

<node	id="c3"
		text="c3" />

<node	id="c4"
		text="c4" />

<node	id="c5"
		text="c5" />

<node	id="c6"
		text="c6" />

<node	id="c7"
		text="c7" />

<node	id="c8"
		text="c8" />

<edge	id="e1"
		src_port="c1"
		dest_port="c2" />

<edge	id="e2"
		src_port="c2"
		dest_port="c0" />

<edge	id="e4"
		src_port="c1"
		dest_port="c3" />

<edge	id="e4"
		src_port="c3"
		dest_port="c0" />

<edge	id="e5"
		src_port="c1"
		dest_port="c4" />

<edge	id="e6"
		src_port="c4"
		dest_port="c5" />

<edge	id="e6"
		src_port="c1"
		dest_port="c6" />

<edge	id="e6"
		src_port="c6"
		dest_port="c7" />

<edge	id="e6"
		src_port="c8"
		dest_port="c1" />

<group id="g0"
		contents="[c0, c1, c2, c3, c4, c6]"
    text="group 0" />
